# Generated by Django 4.2 on 2026-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="例如：USDT、BTC、ETH等",
                        max_length=10,
                        unique=True,
                        verbose_name="貨幣代碼",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：Tether、Bitcoin、Ethereum等",
                        max_length=50,
                        verbose_name="貨幣名稱",
                    ),
                ),
            ],
            options={
                "verbose_name": "貨幣",
                "verbose_name_plural": "貨幣",
            },
        ),
    ]
