# Generated by Django 5.2 on 2026-06-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPairModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('symbol', models.CharField(default='', max_length=20, verbose_name='幣對名稱')),
                ('is_active', models.BooleanField(default=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_pairs', to='currency.currencymodel', verbose_name='標的貨幣')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_pairs', to='currency.currencymodel', verbose_name='計價貨幣')),
            ],
            options={
                'verbose_name': '幣對',
                'verbose_name_plural': '幣對',
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'symbol'), name='unique_currency_pair')],
            },
        ),
    ]
