# Generated by Django 5.2 on 2026-06-18 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_tradingpairmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpairmodel',
            name='base_currency',
            field=models.ForeignKey(help_text='買進或賣出的東西', on_delete=django.db.models.deletion.CASCADE, related_name='base_pairs', to='currency.currencymodel', verbose_name='標的貨幣'),
        ),
    ]
