# Generated by Django 5.2 on 2026-06-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_tradingpairmodel_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpairmodel',
            name='base_currency',
            field=models.ForeignKey(help_text='買進或賣出的貨幣', on_delete=django.db.models.deletion.CASCADE, related_name='base_pairs', to='currency.currencymodel', verbose_name='基準貨幣'),
        ),
        migrations.AlterField(
            model_name='tradingpairmodel',
            name='quote_currency',
            field=models.ForeignKey(help_text='計算的貨幣', on_delete=django.db.models.deletion.CASCADE, related_name='quote_pairs', to='currency.currencymodel', verbose_name='報價貨幣'),
        ),
    ]
