# Generated by Django 5.2 on 2026-07-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_tradingpairmodel_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalTenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='代號')),
                ('name', models.CharField(max_length=10, verbose_name='名稱')),
                ('enable', models.BooleanField(default=False, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '法幣',
                'verbose_name_plural': '法幣',
            },
        ),
        migrations.AddField(
            model_name='currencymodel',
            name='fiat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='1該幣=多少法幣', max_digits=20, verbose_name='與法幣兌換匯率'),
        ),
        migrations.AddConstraint(
            model_name='currencymodel',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_virtual_code_name'),
        ),
        migrations.AddConstraint(
            model_name='legaltendermodel',
            constraint=models.UniqueConstraint(fields=('code', 'name'), name='unique_legal_code_name'),
        ),
        migrations.AddConstraint(
            model_name='legaltendermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('enable', True)), fields=('enable',), name='unique_enable_true'),
        ),
    ]
