# Generated by Django 5.2 on 2026-06-26 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0005_alter_tradingpairmodel_base_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FREEZE', '下單凍結'), ('UNFREEZE', '取消解凍'), ('SETTLE', '結算'), ('REFUND', '多凍結退款'), ('DEPOSIT', '入金'), ('WITHDRAW', '出金'), ('TRADING_FEE', '交易手續費')], max_length=20, verbose_name='變動原因')),
                ('balance_field', models.CharField(choices=[('AVAILABLE', '可用'), ('FROZEN', '凍結')], max_length=20, verbose_name='變動的balance欄位')),
                ('delta', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='變動量(有+-號)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='balance_field變動後的值')),
                ('ref_type', models.CharField(help_text='用model名稱，沒有則為manual', max_length=32, verbose_name='事件來源')),
                ('ref_id', models.CharField(help_text='用model id，沒有則為""，DEX時可存 hash', max_length=32, verbose_name='事件來源id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currencymodel', verbose_name='哪個幣別的錢包')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '帳本流水帳',
                'verbose_name_plural': '帳本流水帳',
            },
        ),
    ]
