# Generated by Django 5.2 on 2026-07-14 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_tradingpairmodel_base_currency_and_more'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentrymodel',
            name='reason',
            field=models.CharField(choices=[('FREEZE', '下單凍結'), ('UNFREEZE', '取消後解凍'), ('SETTLE', '結算'), ('REFUND', '全部成交多凍結退款'), ('DEPOSIT', '入金'), ('WITHDRAW', '出金'), ('TRADING_FEE', '交易手續費')], max_length=20, verbose_name='變動原因'),
        ),
        migrations.CreateModel(
            name='DepositWithdrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='金額')),
                ('direction', models.CharField(choices=[('DEPOSIT', '入金'), ('WITHDRAW', '出金')], max_length=20, verbose_name='變動方向')),
                ('status', models.CharField(choices=[('PENDING', '處理中'), ('DONE', '完成'), ('FAILED', '失敗')], max_length=20, verbose_name='狀態')),
                ('tx_hash', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currencymodel', verbose_name='哪個幣別的錢包')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '出入金紀錄',
                'verbose_name_plural': '出入金紀錄',
            },
        ),
    ]
