# Generated by Django 4.2 on 2026-06-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
        ("member", "0002_userprofilemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilemodel",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="userprofilemodel",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="電話號碼"
            ),
        ),
        migrations.AlterField(
            model_name="walletmodel",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="currency.currencymodel",
                verbose_name="資產類型",
            ),
        ),
    ]
