# Generated by Django 4.2 on 2026-06-04 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0003_alter_userprofilemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='walletmodel',
            unique_together={('user', 'asset_type')},
        ),
    ]
