# Generated by Django 5.2 on 2026-06-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_walletmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='encrypted_totp_secret',
            field=models.BinaryField(default=b'', verbose_name='加密後的TOTP金鑰'),
        ),
    ]
