# Generated by Django 5.2 on 2026-06-25 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_tradingpairmodel_base_currency_and_more'),
        ('member', '0006_userprofilemodel_two_factor_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='walletmodel',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='walletmodel',
            constraint=models.CheckConstraint(condition=models.Q(('frozen_balance__gte', 0)), name='frozen_non_negative'),
        ),
    ]
