# Generated by Django 5.2 on 2026-07-23 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_walletmodel_available_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='證件號碼'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='latest_kyc_status',
            field=models.CharField(choices=[('UNVERIFIED', '未驗證'), ('VERIFYING', '審核中'), ('APPROVED', '已通過'), ('REJECTED', '已拒絕')], default='UNVERIFIED', max_length=20, verbose_name='當前kyc狀態'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='legal_name',
            field=models.CharField(default='', max_length=100, verbose_name='法定姓名'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='國籍碼'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
        migrations.CreateModel(
            name='KycRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('event_status', models.CharField(choices=[('SUBMITTED', '送審'), ('APPROVED', '通過'), ('REJECTED', '拒絕'), ('REVOKED', '撤銷'), ('REVERIFY_REQUIRED', '要求重驗')], max_length=20, verbose_name='事件類型')),
                ('legal_name', models.CharField(default='', max_length=100, verbose_name='送審的法定姓名')),
                ('id_number', models.CharField(blank=True, default='', max_length=100, verbose_name='送審的證件號碼')),
                ('birth_date', models.DateField(blank=True, default=None, null=True, verbose_name='送審的生日')),
                ('nationality', models.CharField(blank=True, default='', max_length=50, verbose_name='送審的國籍碼')),
                ('reject_reason', models.TextField(blank=True, default='', max_length=50, verbose_name='拒絕理由')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='經辦人員')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL, verbose_name='誰的事件')),
            ],
            options={
                'verbose_name': 'KYC 紀錄',
                'verbose_name_plural': 'KYC 紀錄',
            },
        ),
    ]
