# Generated by Django 5.2 on 2026-07-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_kycrecordmodel_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycrecordmodel',
            old_name='reject_reason',
            new_name='reason',
        ),
    ]
