# Generated by Django 5.2 on 2026-07-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_kycrecordmodel_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'permissions': [('review_kyc', '可以審核kyc')], 'verbose_name': '用戶其他資料', 'verbose_name_plural': '用戶其他資料'},
        ),
        migrations.AlterModelOptions(
            name='walletmodel',
            options={'permissions': [('can_deposit', '可以入金')], 'verbose_name': '錢包', 'verbose_name_plural': '錢包'},
        ),
    ]
