# Generated by Django 5.2 on 2026-07-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_userprofilemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='kyc_tier',
            field=models.IntegerField(choices=[(0, '高風險'), (1, '一般風險'), (2, '低風險')], default=0, verbose_name='kyc/風險 等級'),
        ),
    ]
