# Generated by Django 4.2 on 2026-06-03 09:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=20,
                        unique=True,
                        verbose_name="訂單代號",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="數量"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="價格"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("BUY", "買"), ("SELL", "賣")],
                        help_text="例如：買、賣等",
                        max_length=10,
                        verbose_name="訂單類型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("PARTIALLY_FILLED", "部分成交"),
                            ("FILLED", "已成交"),
                            ("CANCELED", "已取消"),
                        ],
                        help_text="例如：等待中、部分成交、已取消等",
                        max_length=20,
                        verbose_name="訂單狀態",
                    ),
                ),
                (
                    "currency1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_currency",
                        to="currency.currencymodel",
                        verbose_name="貨幣1",
                    ),
                ),
                (
                    "currency2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_currency",
                        to="currency.currencymodel",
                        verbose_name="貨幣2",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單",
                "verbose_name_plural": "訂單",
            },
        ),
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=20,
                        unique=True,
                        verbose_name="交易代號",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交數量"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交價格"
                    ),
                ),
                (
                    "order1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buy_order",
                        to="transaction.ordermodel",
                        verbose_name="買單",
                    ),
                ),
                (
                    "order2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sell_order",
                        to="transaction.ordermodel",
                        verbose_name="賣單",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易",
                "verbose_name_plural": "交易",
            },
        ),
    ]
