# Generated by Django 4.2 on 2026-06-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "等待中"),
                    ("PARTIALLY_FILLED", "部分成交"),
                    ("FILLED", "已成交"),
                    ("CANCELED", "已取消"),
                ],
                default="PENDING",
                help_text="例如：等待中、部分成交、已取消等",
                max_length=20,
                verbose_name="訂單狀態",
            ),
        ),
    ]
