# Generated by Django 4.2 on 2026-06-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('transaction', '0002_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='currency1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_currency', to='currency.currencymodel', verbose_name='出去的貨幣'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='currency2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_currency', to='currency.currencymodel', verbose_name='進來的貨幣'),
        ),
    ]
