# Generated by Django 4.2 on 2026-06-04 08:40

import common.func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_ordermodel_currency1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_number',
            field=models.CharField(default=common.func.generate_hex_uuid, max_length=32, unique=True, verbose_name='訂單代號'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_number',
            field=models.CharField(default=common.func.generate_hex_uuid, max_length=32, unique=True, verbose_name='交易代號'),
        ),
    ]
