# Generated by Django 5.2 on 2026-06-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_tradingpairmodel'),
        ('transaction', '0004_alter_ordermodel_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='currency1',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='currency2',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='trading_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_pair_orders', to='currency.tradingpairmodel', verbose_name='幣對'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='trading_pair_symbol',
            field=models.CharField(default='', max_length=20, verbose_name='幣對名稱'),
        ),
    ]
