# Generated by Django 5.2 on 2026-06-18 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_ordermodel_currency1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='order1',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='order2',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='buy_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_transactions', to='transaction.ordermodel', verbose_name='買單'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='sell_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_transactions', to='transaction.ordermodel', verbose_name='賣單'),
        ),
    ]
