# Generated by Django 5.2 on 2026-06-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_transactionmodel_order1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待中'), ('PARTIALLY_FILLED', '部分成交'), ('FULLY_FILLED', '全部成交'), ('CANCELED', '已取消')], default='PENDING', help_text='例如：等待中、部分成交、已取消等', max_length=20, verbose_name='訂單狀態'),
        ),
    ]
