# Generated by Django 5.2 on 2026-06-18 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下單時間'),
        ),
    ]
