# Generated by Django 5.2 on 2026-06-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_ordermodel_ordered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='amount',
            new_name='quantity',
        ),
    ]
